name: ✨ Feature Request
description: 新機能の提案はこちら
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        新しいアイデアの提案ありがとうございます！  
        できるだけ検討しやすいよう、以下の項目をご記入ください。

  - type: input
    id: summary
    attributes:
      label: 機能の概要
      placeholder: ダークモードに対応してほしい など
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: この機能が必要な理由 / 解決したい問題
      placeholder: 夜間作業時に画面が眩しいため、など
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 希望する解決方法
      placeholder: 設定画面からテーマを切り替えられるようにしてほしい、など
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案（もしあれば）
      placeholder: ブラウザ拡張機能で何とかしている、など
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: その他（補足）
      placeholder: スクリーンショットや参考URLなど
    validations:
      required: false
